name: Lint and Test
on: [push]

jobs:

  lint:
    name: Linting
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          version: 12
      - name: Install dependencies
        run: npm ci
      - name: Lint CSS
        run: npm run lint:css
      - name: Lint JavaScript
        run: npm run lint:js

  test:
    name: Unit testing (Node.js ${{ matrix.node }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [10, 12]
        os: [ubuntu-18.04, macOS-10.14, windows-2019]
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test:unit
